- name: creating the payment service
  hosts: payment
  become: true

  tasks:
    - name: install python3 and pip
      ansible.builtin.dnf:
        name:
          - python3
          - python3-pip
        state: present

    - name: create a roboshop user
      ansible.builtin.user:
        name: roboshop
        system: true
        home: /app
        shell: /sbin/nologin
        comment: "Roboshop user"
        create_home: true

    - name: create app directory
      ansible.builtin.file:
        name: /app
        state: directory

    - name: Download payment service code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
        dest: /tmp/payment.zip

    - name: extract the payment service code
      ansible.builtin.unarchive:
        src: /tmp/payment.zip
        dest: /app
        remote_src: yes
        owner: roboshop
        group: roboshop

    - name: install python dependencies
      ansible.builtin.pip:
        requirements: requirements.txt
        executable: pip3
      args:
        chdir: /app

    - name: copy the payment service
      ansible.builtin.copy:
        src: service/payment.service
        dest: /etc/systemd/system/payment.service

    - name: reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: start and enable payment service
      ansible.builtin.service:
        name: payment
        state: started
        enabled: true

