- name: setting up the userserver
  hosts: user
  become: true

  tasks:

    - name: disable nodejs 
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs 20
      ansible.builtin.command: dnf module enable nodejs:20 -y
 
    - name: install node js
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: create a roboshop user
      ansible.builtin.user:
        name: roboshop
        comment: "Roboshop User"
        shell: /sbin/nologin
        home: /app
        system: true

    - name: create a file directory
      ansible.builtin.file:
        path: /app
        state: directory
    
    - name: download the user file in temporary location
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
        dest: /tmp/user.zip

    - name: extract the user zip file in the app directory
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes # it checks files exits in the remote server(user) or not

    - name: install npm dependencies
      community.general.npm:
        path: /app

    - name: copy systemd service file
      ansible.builtin.copy:
        src: service/user.service
        dest: /etc/systemd/system/user.service

    - name: system daemon reload
      ansible.builtin.systemd:
        daemon-reload: yes

    - name: start and enable user service
      ansible.builtin.service:
        name: user
        state: started
        enabled: yes

